import Head from "next/head";
import One from "../components/questions/1";
import styles from "../styles/Home.module.css";
import { Component } from "react";
import { IHomeProps, IHomeState } from "../interfaces";
import Welcome from "../components/Welcome";

export default class Home extends Component<IHomeProps, IHomeState> {
  constructor(public readonly props: IHomeProps) {
    super(props);
    this.state = {
      welcome: true,
    };
    this.visibilityHandler = this.visibilityHandler.bind(this);
  }

  visibilityHandler() {
    this.setState({
      welcome: false,
    });
  }

  render() {
    setTimeout(() => {
      this.visibilityHandler();
    }, 3000);

    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {
          this.state.welcome ? <Welcome /> : null
          // <One />
        }
      </div>
    );
  }
}
